<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>07b30b67-338a-4062-afb8-87ad37cfbfaa</UserSecretsId>
      <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CSnakes.Runtime" Version="2.0.0-beta.319" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.6.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NumCalc.Calculation.Business\NumCalc.Calculation.Business.csproj" />
        <ProjectReference Include="..\NumCalc.Shared\NumCalc.Shared.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>
</Project>
