//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumCalc.UI.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumCalc.UI.Shared.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this topic.
        /// </summary>
        public static string AboutThisTopic {
            get {
                return ResourceManager.GetString("AboutThisTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your profile, change your password, or delete your account.
        /// </summary>
        public static string AccountSettingsDesc {
            get {
                return ResourceManager.GetString("AccountSettingsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected.
        /// </summary>
        public static string AllSelected {
            get {
                return ResourceManager.GetString("AllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis mode.
        /// </summary>
        public static string AnalysisMode {
            get {
                return ResourceManager.GetString("AnalysisMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply and recognize.
        /// </summary>
        public static string ApplyAndRecognize {
            get {
                return ResourceManager.GetString("ApplyAndRecognize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument x.
        /// </summary>
        public static string ArgumentX {
            get {
                return ResourceManager.GetString("ArgumentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward Difference.
        /// </summary>
        public static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benchmark.
        /// </summary>
        public static string Benchmark {
            get {
                return ResourceManager.GetString("Benchmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation History.
        /// </summary>
        public static string CalculationHistory {
            get {
                return ResourceManager.GetString("CalculationHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Difference.
        /// </summary>
        public static string Central {
            get {
                return ResourceManager.GetString("Central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your interface language.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Calculate to view the result.
        /// </summary>
        public static string ClickCalculateToViewResult {
            get {
                return ResourceManager.GetString("ClickCalculateToViewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined.
        /// </summary>
        public static string Combined {
            get {
                return ResourceManager.GetString("Combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm changes.
        /// </summary>
        public static string ConfirmChanges {
            get {
                return ResourceManager.GetString("ConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password to apply the changes.
        /// </summary>
        public static string ConfirmChangesDesc {
            get {
                return ResourceManager.GetString("ConfirmChangesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue as guest.
        /// </summary>
        public static string ContinueAsGuest {
            get {
                return ResourceManager.GetString("ContinueAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy LaTeX.
        /// </summary>
        public static string CopyLaTeX {
            get {
                return ResourceManager.GetString("CopyLaTeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cramer&apos;s Rule.
        /// </summary>
        public static string Cramer {
            get {
                return ResourceManager.GetString("Cramer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview of your recent calculations, saved inputs, and exported files.
        /// </summary>
        public static string DashboardDesc {
            get {
                return ResourceManager.GetString("DashboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete my account.
        /// </summary>
        public static string DeleteAccountConfirm {
            get {
                return ResourceManager.GetString("DeleteAccountConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your current password to confirm account deletion.
        /// </summary>
        public static string DeleteAccountConfirmDesc {
            get {
                return ResourceManager.GetString("DeleteAccountConfirmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete your account along with your history, saved inputs and exported files. This action cannot be undone.
        /// </summary>
        public static string DeleteAccountDesc {
            get {
                return ResourceManager.GetString("DeleteAccountDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivative order.
        /// </summary>
        public static string DerivativeOrder {
            get {
                return ResourceManager.GetString("DerivativeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dichotomy.
        /// </summary>
        public static string Dichotomy {
            get {
                return ResourceManager.GetString("Dichotomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dichotomy method.
        /// </summary>
        public static string DICHOTOMY_METHOD {
            get {
                return ResourceManager.GetString("DICHOTOMY_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differentiation.
        /// </summary>
        public static string Differentiation {
            get {
                return ResourceManager.GetString("Differentiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerically compute first and second derivatives of functions.
        /// </summary>
        public static string DifferentiationDesc {
            get {
                return ResourceManager.GetString("DifferentiationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DoNotHaveAccount {
            get {
                return ResourceManager.GetString("DoNotHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End point.
        /// </summary>
        public static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equation is required.
        /// </summary>
        public static string EquationIsRequired {
            get {
                return ResourceManager.GetString("EquationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equations.
        /// </summary>
        public static string Equations {
            get {
                return ResourceManager.GetString("Equations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equation Systems.
        /// </summary>
        public static string EquationSystems {
            get {
                return ResourceManager.GetString("EquationSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve linear and non-linear systems of equations.
        /// </summary>
        public static string EquationSystemsDesc {
            get {
                return ResourceManager.GetString("EquationSystemsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while applying and recognizing.
        /// </summary>
        public static string ErrorOccurredWhileApplyingAndRecognizing {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileApplyingAndRecognizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler.
        /// </summary>
        public static string Euler {
            get {
                return ResourceManager.GetString("Euler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler Improved (Heun).
        /// </summary>
        public static string EulerImproved {
            get {
                return ResourceManager.GetString("EulerImproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF.
        /// </summary>
        public static string ExportPdf {
            get {
                return ResourceManager.GetString("ExportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression contains a syntax error.
        /// </summary>
        public static string ExpressionInvalid {
            get {
                return ResourceManager.GetString("ExpressionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression must contain only the variable x.
        /// </summary>
        public static string ExpressionOnlyX {
            get {
                return ResourceManager.GetString("ExpressionOnlyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a function expression.
        /// </summary>
        public static string ExpressionRequired {
            get {
                return ResourceManager.GetString("ExpressionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive charts.
        /// </summary>
        public static string FeatureCharts {
            get {
                return ResourceManager.GetString("FeatureCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF export.
        /// </summary>
        public static string FeaturePdf {
            get {
                return ResourceManager.GetString("FeaturePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step-by-step solutions.
        /// </summary>
        public static string FeatureStepByStep {
            get {
                return ResourceManager.GetString("FeatureStepByStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finite differences.
        /// </summary>
        public static string FiniteDifferences {
            get {
                return ResourceManager.GetString("FiniteDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed-Point Iteration.
        /// </summary>
        public static string FixedPoint {
            get {
                return ResourceManager.GetString("FixedPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email associated with your account and we will send you a link to reset your password.
        /// </summary>
        public static string ForgotPasswordIntro {
            get {
                return ResourceManager.GetString("ForgotPasswordIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an account with that email exists, we have sent a link to reset your password. The link expires in 30 minutes.
        /// </summary>
        public static string ForgotPasswordSubmittedNotice {
            get {
                return ResourceManager.GetString("ForgotPasswordSubmittedNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Difference.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function expression.
        /// </summary>
        public static string FunctionExpression {
            get {
                return ResourceManager.GetString("FunctionExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function value.
        /// </summary>
        public static string FunctionValue {
            get {
                return ResourceManager.GetString("FunctionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian Elimination.
        /// </summary>
        public static string Gauss {
            get {
                return ResourceManager.GetString("Gauss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden Section.
        /// </summary>
        public static string GoldenSection {
            get {
                return ResourceManager.GetString("GoldenSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient descent.
        /// </summary>
        public static string GradientDescent {
            get {
                return ResourceManager.GetString("GradientDescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left endpoint a of the search interval [a, b]. Must satisfy f(a)·f(b) &lt; 0 for bracketing methods.
        /// </summary>
        public static string Hint_BracketingLowerBound {
            get {
                return ResourceManager.GetString("Hint_BracketingLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order of the derivative to compute: 1 for f&apos;(x), 2 for f&apos;&apos;(x).
        /// </summary>
        public static string Hint_DerivativeOrder {
            get {
                return ResourceManager.GetString("Hint_DerivativeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function f(x) to differentiate. Use standard math notation, e.g. sin(x), x^2 + 3*x.
        /// </summary>
        public static string Hint_DiffFunction {
            get {
                return ResourceManager.GetString("Hint_DiffFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function f(x) to differentiate symbolically via Lagrange polynomial interpolation.
        /// </summary>
        public static string Hint_DiffFunctionLagrange {
            get {
                return ResourceManager.GetString("Hint_DiffFunctionLagrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop when the gradient norm falls below this value.
        /// </summary>
        public static string Hint_GradientNormTolerance {
            get {
                return ResourceManager.GetString("Hint_GradientNormTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting point x₀ for the iterative method. Choose a value close to the expected root or solution for faster convergence.
        /// </summary>
        public static string Hint_InitialGuess {
            get {
                return ResourceManager.GetString("Hint_InitialGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial x value x₀ — the starting point of the solution interval.
        /// </summary>
        public static string Hint_InitialX {
            get {
                return ResourceManager.GetString("Hint_InitialX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial condition y(x₀) = y₀.
        /// </summary>
        public static string Hint_InitialY {
            get {
                return ResourceManager.GetString("Hint_InitialY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrand f(x). The definite integral ∫f(x)dx is computed numerically over [a, b].
        /// </summary>
        public static string Hint_Integrand {
            get {
                return ResourceManager.GetString("Hint_Integrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function f(x) to interpolate. The polynomial is built through sample points generated from this expression.
        /// </summary>
        public static string Hint_InterpFunction {
            get {
                return ResourceManager.GetString("Hint_InterpFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop when the interval length is below this value. Controls the precision of the golden section search.
        /// </summary>
        public static string Hint_IntervalLengthTolerance {
            get {
                return ResourceManager.GetString("Hint_IntervalLengthTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sub-intervals n. More intervals improve accuracy at the cost of computation time.
        /// </summary>
        public static string Hint_Intervals {
            get {
                return ResourceManager.GetString("Hint_Intervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration function g&lt;sub&gt;{0}&lt;/sub&gt;(x). Rewrite f&lt;sub&gt;{0}&lt;/sub&gt;(x) = 0 as x&lt;sub&gt;{0}&lt;/sub&gt; = g&lt;sub&gt;{0}&lt;/sub&gt;(x) for fixed-point / Seidel iteration.
        /// </summary>
        public static string Hint_IterationFunction {
            get {
                return ResourceManager.GetString("Hint_IterationFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step multiplier α for gradient descent. Too large causes divergence; too small causes slow convergence. Typical range: 0.001 – 0.1.
        /// </summary>
        public static string Hint_LearningRate {
            get {
                return ResourceManager.GetString("Hint_LearningRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left endpoint a of the search interval [a, b]. Must be less than the upper bound.
        /// </summary>
        public static string Hint_LowerBound {
            get {
                return ResourceManager.GetString("Hint_LowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of iterations allowed before stopping. Increase if the method has not yet converged within the tolerance.
        /// </summary>
        public static string Hint_MaxIterations {
            get {
                return ResourceManager.GetString("Hint_MaxIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective function f(x) to minimize over [a, b].
        /// </summary>
        public static string Hint_ObjectiveFunc1D {
            get {
                return ResourceManager.GetString("Hint_ObjectiveFunc1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration step h. Smaller h gives higher accuracy but more computation steps. Estimated steps:.
        /// </summary>
        public static string Hint_OdeStep {
            get {
                return ResourceManager.GetString("Hint_OdeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective function to minimize. Variables are detected alphabetically from the expression, e.g. x1^2 + x2^2.
        /// </summary>
        public static string Hint_OptObjective {
            get {
                return ResourceManager.GetString("Hint_OptObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of successive approximation steps k in Picard&apos;s method. Higher values are more accurate near x₀ but diverge further away.
        /// </summary>
        public static string Hint_PicardOrder {
            get {
                return ResourceManager.GetString("Hint_PicardOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picard&apos;s method is symbolic and converges only near x₀. Keep |x_target − x₀| small (typically &lt; 1).&lt;br/&gt;&lt;br/&gt;Higher approximation order on wide intervals will diverge or be very slow.
        /// </summary>
        public static string Hint_PicardWarning {
            get {
                return ResourceManager.GetString("Hint_PicardWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The point x* at which to evaluate the interpolated or differentiated value.
        /// </summary>
        public static string Hint_QueryPoint {
            get {
                return ResourceManager.GetString("Hint_QueryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed error ε. The algorithm stops when the interval width or residual is below ε.
        /// </summary>
        public static string Hint_RootTolerance {
            get {
                return ResourceManager.GetString("Hint_RootTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step size h used in finite-difference formulas. Smaller h reduces truncation error but increases round-off error. Default 0.001 is a safe starting point.
        /// </summary>
        public static string Hint_StepSize {
            get {
                return ResourceManager.GetString("Hint_StepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial guess for x&lt;sub&gt;{0}&lt;/sub&gt;. Choose a value close to the expected solution.
        /// </summary>
        public static string Hint_SystemInitialGuess {
            get {
                return ResourceManager.GetString("Hint_SystemInitialGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target x value at which y is approximated. For Picard, keep |x_target − x₀| small (typically &lt; 1).
        /// </summary>
        public static string Hint_TargetX {
            get {
                return ResourceManager.GetString("Hint_TargetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed error between successive iterations. Smaller values give more precise results but require more iterations (e.g. 0.0001).
        /// </summary>
        public static string Hint_Tolerance {
            get {
                return ResourceManager.GetString("Hint_Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of uniformly spaced sample points. More points improve accuracy at the cost of computation time.
        /// </summary>
        public static string Hint_UniformPoints {
            get {
                return ResourceManager.GetString("Hint_UniformPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right endpoint b of the search interval [a, b]. Must be greater than the lower bound.
        /// </summary>
        public static string Hint_UpperBound {
            get {
                return ResourceManager.GetString("Hint_UpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation nodes xᵢ — the x-coordinates of the known data points. Must be distinct and sorted in ascending order.
        /// </summary>
        public static string Hint_XNodes {
            get {
                return ResourceManager.GetString("Hint_XNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your function or paste data points into the input field.
        /// </summary>
        public static string HowItWorksStep1Desc {
            get {
                return ResourceManager.GetString("HowItWorksStep1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter expression.
        /// </summary>
        public static string HowItWorksStep1Title {
            get {
                return ResourceManager.GetString("HowItWorksStep1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the numerical algorithm that fits your problem.
        /// </summary>
        public static string HowItWorksStep2Desc {
            get {
                return ResourceManager.GetString("HowItWorksStep2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a method.
        /// </summary>
        public static string HowItWorksStep2Title {
            get {
                return ResourceManager.GetString("HowItWorksStep2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore step-by-step solutions, interactive charts, and export to PDF.
        /// </summary>
        public static string HowItWorksStep3Desc {
            get {
                return ResourceManager.GetString("HowItWorksStep3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View results &amp; export.
        /// </summary>
        public static string HowItWorksStep3Title {
            get {
                return ResourceManager.GetString("HowItWorksStep3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string HowItWorksTitle {
            get {
                return ResourceManager.GetString("HowItWorksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial guess.
        /// </summary>
        public static string InitialGuess {
            get {
                return ResourceManager.GetString("InitialGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial point.
        /// </summary>
        public static string InitialPoint {
            get {
                return ResourceManager.GetString("InitialPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial X.
        /// </summary>
        public static string InitialX {
            get {
                return ResourceManager.GetString("InitialX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Y.
        /// </summary>
        public static string InitialY {
            get {
                return ResourceManager.GetString("InitialY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral.
        /// </summary>
        public static string Integral {
            get {
                return ResourceManager.GetString("Integral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        public static string Integration {
            get {
                return ResourceManager.GetString("Integration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate definite integrals using rectangle, trapezoid, or Simpson rules.
        /// </summary>
        public static string IntegrationDesc {
            get {
                return ResourceManager.GetString("IntegrationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolated value.
        /// </summary>
        public static string InterpolatedValue {
            get {
                return ResourceManager.GetString("InterpolatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation.
        /// </summary>
        public static string Interpolation {
            get {
                return ResourceManager.GetString("Interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate f(x) between known data points using polynomials or splines.
        /// </summary>
        public static string InterpolationDesc {
            get {
                return ResourceManager.GetString("InterpolationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervals.
        /// </summary>
        public static string Intervals {
            get {
                return ResourceManager.GetString("Intervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient descent.
        /// </summary>
        public static string IsGradientDescent {
            get {
                return ResourceManager.GetString("IsGradientDescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iteration functions.
        /// </summary>
        public static string IterationFunctions {
            get {
                return ResourceManager.GetString("IterationFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        public static string Iterations {
            get {
                return ResourceManager.GetString("Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagrange.
        /// </summary>
        public static string Lagrange {
            get {
                return ResourceManager.GetString("Lagrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning rate.
        /// </summary>
        public static string LearningRate {
            get {
                return ResourceManager.GetString("LearningRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string Linear {
            get {
                return ResourceManager.GetString("Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load inputs.
        /// </summary>
        public static string LoadInputs {
            get {
                return ResourceManager.GetString("LoadInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower bound.
        /// </summary>
        public static string LowerBound {
            get {
                return ResourceManager.GetString("LowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A numerical methods computation platform for root finding, interpolation, integration, and more.
        /// </summary>
        public static string MainHeroSubtitle {
            get {
                return ResourceManager.GetString("MainHeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical Methods Calculator.
        /// </summary>
        public static string MainHeroTitle {
            get {
                return ResourceManager.GetString("MainHeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max iterations.
        /// </summary>
        public static string MaxIterations {
            get {
                return ResourceManager.GetString("MaxIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bisection.
        /// </summary>
        public static string Method_Bisection {
            get {
                return ResourceManager.GetString("Method_Bisection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined (Brent).
        /// </summary>
        public static string Method_Combined {
            get {
                return ResourceManager.GetString("Method_Combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cramer&apos;s Rule.
        /// </summary>
        public static string Method_Cramer {
            get {
                return ResourceManager.GetString("Method_Cramer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Spline.
        /// </summary>
        public static string Method_CubicSpline {
            get {
                return ResourceManager.GetString("Method_CubicSpline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler.
        /// </summary>
        public static string Method_Euler {
            get {
                return ResourceManager.GetString("Method_Euler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euler Improved (Heun).
        /// </summary>
        public static string Method_EulerImproved {
            get {
                return ResourceManager.GetString("Method_EulerImproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finite Differences.
        /// </summary>
        public static string Method_FiniteDiff {
            get {
                return ResourceManager.GetString("Method_FiniteDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed-point Iteration.
        /// </summary>
        public static string Method_FixedPoint {
            get {
                return ResourceManager.GetString("Method_FixedPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian Elimination.
        /// </summary>
        public static string Method_Gaussian {
            get {
                return ResourceManager.GetString("Method_Gaussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauss-Seidel.
        /// </summary>
        public static string Method_GaussSeidel {
            get {
                return ResourceManager.GetString("Method_GaussSeidel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden Section.
        /// </summary>
        public static string Method_GoldenSection {
            get {
                return ResourceManager.GetString("Method_GoldenSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient Descent.
        /// </summary>
        public static string Method_GradientDescent {
            get {
                return ResourceManager.GetString("Method_GradientDescent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagrange Derivative.
        /// </summary>
        public static string Method_LagrangeDeriv {
            get {
                return ResourceManager.GetString("Method_LagrangeDeriv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagrange Polynomial.
        /// </summary>
        public static string Method_LagrangePoly {
            get {
                return ResourceManager.GetString("Method_LagrangePoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newton-Raphson.
        /// </summary>
        public static string Method_Newton {
            get {
                return ResourceManager.GetString("Method_Newton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newton Polynomial.
        /// </summary>
        public static string Method_NewtonPoly {
            get {
                return ResourceManager.GetString("Method_NewtonPoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picard.
        /// </summary>
        public static string Method_Picard {
            get {
                return ResourceManager.GetString("Method_Picard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle Rule.
        /// </summary>
        public static string Method_Rectangle {
            get {
                return ResourceManager.GetString("Method_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runge-Kutta 2.
        /// </summary>
        public static string Method_RK2 {
            get {
                return ResourceManager.GetString("Method_RK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runge-Kutta 4.
        /// </summary>
        public static string Method_RK4 {
            get {
                return ResourceManager.GetString("Method_RK4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secant.
        /// </summary>
        public static string Method_Secant {
            get {
                return ResourceManager.GetString("Method_Secant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Iteration.
        /// </summary>
        public static string Method_SimpleIteration {
            get {
                return ResourceManager.GetString("Method_SimpleIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpson&apos;s 1/3 Rule.
        /// </summary>
        public static string Method_Simpson {
            get {
                return ResourceManager.GetString("Method_Simpson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapezoid Rule.
        /// </summary>
        public static string Method_Trapezoid {
            get {
                return ResourceManager.GetString("Method_Trapezoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Search.
        /// </summary>
        public static string Method_UniformSearch {
            get {
                return ResourceManager.GetString("Method_UniformSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string Methods {
            get {
                return ResourceManager.GetString("Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midpoint.
        /// </summary>
        public static string Midpoint {
            get {
                return ResourceManager.GetString("Midpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Data.
        /// </summary>
        public static string MyData {
            get {
                return ResourceManager.GetString("MyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave empty to keep current.
        /// </summary>
        public static string NewPasswordOptional {
            get {
                return ResourceManager.GetString("NewPasswordOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newton.
        /// </summary>
        public static string Newton {
            get {
                return ResourceManager.GetString("Newton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records yet.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-linear.
        /// </summary>
        public static string NonLinear {
            get {
                return ResourceManager.GetString("NonLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No saved inputs for this calculation type.
        /// </summary>
        public static string NoSavedInputsForType {
            get {
                return ResourceManager.GetString("NoSavedInputsForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported format.
        /// </summary>
        public static string NotSupportedFormat {
            get {
                return ResourceManager.GetString("NotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential Equations.
        /// </summary>
        public static string Ode {
            get {
                return ResourceManager.GetString("Ode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solve ordinary differential equations step by step with initial conditions.
        /// </summary>
        public static string OdeDesc {
            get {
                return ResourceManager.GetString("OdeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimization.
        /// </summary>
        public static string Optimization {
            get {
                return ResourceManager.GetString("Optimization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the minimum of a function in one or multiple dimensions.
        /// </summary>
        public static string OptimizationDesc {
            get {
                return ResourceManager.GetString("OptimizationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picard.
        /// </summary>
        public static string Picard {
            get {
                return ResourceManager.GetString("Picard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picard order.
        /// </summary>
        public static string PicardOrder {
            get {
                return ResourceManager.GetString("PicardOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one method for benchmarking.
        /// </summary>
        public static string PleaseSelectAtLeastOneMethodForBenchmarking {
            get {
                return ResourceManager.GetString("PleaseSelectAtLeastOneMethodForBenchmarking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile information.
        /// </summary>
        public static string ProfileInformation {
            get {
                return ResourceManager.GetString("ProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query point.
        /// </summary>
        public static string QueryPoint {
            get {
                return ResourceManager.GetString("QueryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw data.
        /// </summary>
        public static string RawData {
            get {
                return ResourceManager.GetString("RawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle (Left).
        /// </summary>
        public static string RectangleLeft {
            get {
                return ResourceManager.GetString("RectangleLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle (Midpoint).
        /// </summary>
        public static string RectangleMidpoint {
            get {
                return ResourceManager.GetString("RectangleMidpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle (Right).
        /// </summary>
        public static string RectangleRight {
            get {
                return ResourceManager.GetString("RectangleRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redesign your image.
        /// </summary>
        public static string RedesignYourImage {
            get {
                return ResourceManager.GetString("RedesignYourImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new password for your account.
        /// </summary>
        public static string ResetPasswordIntro {
            get {
                return ResourceManager.GetString("ResetPasswordIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordSubmit {
            get {
                return ResourceManager.GetString("ResetPasswordSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reset link is invalid. Please request a new password reset email.
        /// </summary>
        public static string ResetTokenMissing {
            get {
                return ResourceManager.GetString("ResetTokenMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert change.
        /// </summary>
        public static string RevertChange {
            get {
                return ResourceManager.GetString("RevertChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Finding.
        /// </summary>
        public static string Roots {
            get {
                return ResourceManager.GetString("Roots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find where f(x) = 0 using iterative numerical methods.
        /// </summary>
        public static string RootsDesc {
            get {
                return ResourceManager.GetString("RootsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runge-Kutta 2.
        /// </summary>
        public static string RungeKutta2 {
            get {
                return ResourceManager.GetString("RungeKutta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runge-Kutta 4.
        /// </summary>
        public static string RungeKutta4 {
            get {
                return ResourceManager.GetString("RungeKutta4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Files.
        /// </summary>
        public static string SavedFiles {
            get {
                return ResourceManager.GetString("SavedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Inputs.
        /// </summary>
        public static string SavedInputs {
            get {
                return ResourceManager.GetString("SavedInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select saved inputs.
        /// </summary>
        public static string SavedInputsPickerTitle {
            get {
                return ResourceManager.GetString("SavedInputsPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input set name.
        /// </summary>
        public static string SaveInputName {
            get {
                return ResourceManager.GetString("SaveInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save inputs.
        /// </summary>
        public static string SaveInputs {
            get {
                return ResourceManager.GetString("SaveInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secant.
        /// </summary>
        public static string Secant {
            get {
                return ResourceManager.GetString("Secant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauss-Seidel.
        /// </summary>
        public static string Seidel {
            get {
                return ResourceManager.GetString("Seidel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one method.
        /// </summary>
        public static string SelectAtLeastOneMethod {
            get {
                return ResourceManager.GetString("SelectAtLeastOneMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select items.
        /// </summary>
        public static string SelectItems {
            get {
                return ResourceManager.GetString("SelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send reset link.
        /// </summary>
        public static string SendResetLink {
            get {
                return ResourceManager.GetString("SendResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple iterations.
        /// </summary>
        public static string SimpleIterations {
            get {
                return ResourceManager.GetString("SimpleIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpson&apos;s 1/3.
        /// </summary>
        public static string Simpson {
            get {
                return ResourceManager.GetString("Simpson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spline.
        /// </summary>
        public static string Spline {
            get {
                return ResourceManager.GetString("Spline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point must be less than end point.
        /// </summary>
        public static string StartMustBeLessThanEnd {
            get {
                return ResourceManager.GetString("StartMustBeLessThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start point.
        /// </summary>
        public static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string StatCategories {
            get {
                return ResourceManager.GetString("StatCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string StatExport {
            get {
                return ResourceManager.GetString("StatExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string StatMethods {
            get {
                return ResourceManager.GetString("StatMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step size.
        /// </summary>
        public static string StepSize {
            get {
                return ResourceManager.GetString("StepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target X.
        /// </summary>
        public static string TargetX {
            get {
                return ResourceManager.GetString("TargetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description for this step.
        /// </summary>
        public static string ThereIsNoDescriptionToStep {
            get {
                return ResourceManager.GetString("ThereIsNoDescriptionToStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance.
        /// </summary>
        public static string Tolerance {
            get {
                return ResourceManager.GetString("Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance must be between 1e-10 and 0.1.
        /// </summary>
        public static string ToleranceMustBeReasonable {
            get {
                return ResourceManager.GetString("ToleranceMustBeReasonable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapezoid.
        /// </summary>
        public static string Trapezoid {
            get {
                return ResourceManager.GetString("Trapezoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Search.
        /// </summary>
        public static string UniformSearch {
            get {
                return ResourceManager.GetString("UniformSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper bound.
        /// </summary>
        public static string UpperBound {
            get {
                return ResourceManager.GetString("UpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User dashboard.
        /// </summary>
        public static string UserDashboard {
            get {
                return ResourceManager.GetString("UserDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        public static string Variant {
            get {
                return ResourceManager.GetString("Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X nodes.
        /// </summary>
        public static string XNodes {
            get {
                return ResourceManager.GetString("XNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y values.
        /// </summary>
        public static string YValues {
            get {
                return ResourceManager.GetString("YValues", resourceCulture);
            }
        }
    }
}
